service: jubla-crud-forms-go

provider:
  name: aws
  runtime: go1.x
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "arn:aws:dynamodb:us-east-1:582589677455:table/jubla-forms-responses"

functions:
  read:
    handler: bin/read
    events:
      - httpApi:
          path: /form
          method: get
  create:
    handler: bin/create
    events:
      - httpApi:
          path: /form
          method: post
  delete:
    handler: bin/delete
    events:
      - httpApi:
          path: /form
          method: delete
  update:
    handler: bin/update
    events:
      - httpApi:
          path: /form
          method: put

package:
  patterns:
    - ./bin/**