service: jubla-crud-forms-go

provider:
  name: aws
  runtime: go1.x
  apiGateway:
    binaryMediaType:
      - "multipart/form-data"
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "arn:aws:dynamodb:us-east-1:582589677455:table/jubla-forms-responses"
        - Effect: Allow
          Action:
            - s3:Put*
            - s3:Get*
            - s3:List*
            - s3:Delete*
          Resource: "*"

functions:
  read_structure:
    handler: bin/read_structure
    events:
      - http:
          path: structure/{id}
          method: get
  read:
    handler: bin/read_structure
    events:
      - httpApi:
          path: /form
          method: get
          cors: true # <-- CORS!
  create:
    handler: bin/create
    events:
      - httpApi:
          path: /form
          method: post
          cors: true # <-- CORS!
  delete:
    handler: bin/delete
    events:
      - httpApi:
          path: /form
          method: delete
  update:
    handler: bin/update
    events:
      - httpApi:
          path: /form
          method: put

package:
  patterns:
    - ./bin/**
